# -*- coding: utf-8 -*-
"""To-Do_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4Vi6QeU53Q0EgI3iBM0j1pwA3SSAw7G
"""

try:
    with open("gorevler.txt", "r", encoding="utf-8") as dosya:
        liste = [satir.strip() for satir in dosya.readlines()]
    print("Görevler başarıyla yüklendi.")
except FileNotFoundError:
    liste = []
    print("Görev dosyası bulunamadı. Yeni bir liste oluşturuldu.")

def listeyi_kaydet():
    try:
        with open("gorevler.txt", "w", encoding="utf-8") as dosya:
            for gorev in liste:
                dosya.write(gorev + "\n")
    except Exception as e:
        print("Dosya kaydederken hata oluştu:", e)

while True:
    print("\nTo-Do List Uygulamasına Hoş Geldiniz!")
    print("------- TO-DO LIST UYGULAMASI -------")
    print("1: Görevleri Listele")
    print("2: Yeni Görev Ekle")
    print("3: Görev Düzenle")
    print("4: Görev Sil")
    print("5: Çıkış")
    print("-------------------------------------")

    secim_str = input("Lütfen yapmak istediğiniz işlemin numarasını giriniz: ")

    if secim_str.isdigit():
        secim = int(secim_str)
        if secim == 1:
            print("Görevler listeleniyor...")
            if len(liste) == 0:
                print("Görev listesi boş.")
            else:
                print("--- Görev Listesi ---")
                for i, gorev in enumerate(liste, start=1):
                    print(f"{i}. {gorev}")
        elif secim == 2:
            print("Yeni görev ekleme formu açılıyor...")
            gorev = input("Lütfen görev giriniz: ")
            if gorev.strip() == "":
                print("Boş görev eklenemez!")
            else:
                liste.append(gorev)
                listeyi_kaydet()
                print("Görev eklendi.")
        elif secim == 3:
            print("Görev düzenleme işlemi başlatılıyor...")
            if len(liste) == 0:
                print("Görev listesi boş. Düzenleme yapılamaz.")
            else:
                print("--- Görev Listesi ---")
                for i, gorev in enumerate(liste, start=1):
                    print(f"{i}. {gorev}")
                duzenle_gorev = input("Düzenlemek istediğiniz görevin numarasını girin: ")
                if duzenle_gorev.isdigit():
                    num = int(duzenle_gorev)
                    if 1 <= num <= len(liste):
                        yeni_gorev = input("Yeni görev metni: ")
                        if yeni_gorev.strip() == "":
                            print("Boş görev ile güncelleme yapılamaz!")
                        else:
                            liste[num - 1] = yeni_gorev
                            listeyi_kaydet()
                            print("Görev başarıyla güncellendi.")
                    else:
                        print("Geçersiz görev numarası!")
                else:
                    print("Lütfen geçerli bir sayı girin.")
        elif secim == 4:
            print("Görev silme işlemi başlatılıyor...")
            if len(liste) == 0:
                print("Görev listesi boş. Silme yapılamaz.")
            else:
                print("--- Görev Listesi ---")
                for i, gorev in enumerate(liste, start=1):
                    print(f"{i}. {gorev}")
                sil_gorev = input("Silmek istediğiniz görevin numarasını girin: ")
                if sil_gorev.isdigit():
                    num = int(sil_gorev)
                    if 1 <= num <= len(liste):
                        silinen = liste.pop(num - 1)
                        listeyi_kaydet()
                        print(f"'{silinen}' görevi başarıyla silindi.")
                    else:
                        print("Geçersiz görev numarası!")
                else:
                    print("Lütfen geçerli bir sayı girin.")
        elif secim == 5:
            print("Uygulamadan çıkılıyor...")
            break
        else:
            print(f"Geçersiz seçim: {secim}. Lütfen menüdeki numaralardan birini girin.")
    else:
        print(f"Hatalı giriş: '{secim_str}'. Lütfen sadece sayı girin.")
print("İşlem tamamlandı. Güle güle!")